import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ConfigProvider } from "antd";
import enUS from 'antd/lib/locale/en_US'; 

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // <ConfigProvider
    //   locale={enUS}
    //   getPopupContainer={(trigger) => trigger.parentNode}
    // >
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
    // </ConfigProvider>
  );
}
